version: '3.9'

services:
  db:
    image: postgres:latest2
    container_name: postgresql_sample
    build: ./postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: $POSTGRES_DB
    restart: always
